<h1 class="pt-3">{{ __('About') }}</h1>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <img class="img-fluid" src="{{ theme.avatar }}" width="92" height="92px" alt="">
                    {{ config.author }}
                </h5>
                <p class="card-text"></p>
            </div>
        </div>
    </div>
</div>
